---
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
      - python-pip
      - python3-pip

install:
  # Install ansible
  - pip install ansible ansible-lint yamllint

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - echo -e '[defaults]\nroles_path=../' >ansible.cfg

script:
  # YAML syntax check
  - yamllint .
  # Run ansible-lint
  - ansible-lint .
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
